/* Scripted scenarios for the Mini App harness (dev-only; never deployed).
 * Each scenario configures the mock Telegram client, the mock backend, the steps to
 * perform, and what must be true at the end. See harness.html and run.html. */
(function () {
  var SESSION = {
    sessionId: 'S-20260921-1030',
    opensAt: '2026-09-21T02:30:15.000Z',
    closesAt: '2026-09-21T03:30:15.000Z',
    closesAtText: '11:30',
    startedByName: 'Ada Admin',
  };
  var MEMBER_SESSION = { sessionId: SESSION.sessionId, opensAt: SESSION.opensAt, closesAt: SESSION.closesAt, closesAtText: '11:30' };
  var CHECKED_IN = { ok: true, code: 'CHECKED_IN', message: 'Checked in at 10:32.',
    data: { sessionId: SESSION.sessionId, at: '2026-09-21T02:32:07.000Z', atText: '10:32', closesAt: SESSION.closesAt, closesAtText: '11:30' } };
  function status(data) {
    return { ok: true, code: 'OK', message: '', data: Object.assign({ isAdmin: false, sessionMinutes: 60, activeSession: null, myCheckin: null }, data) };
  }
  var GPS = { latitude: 1.28345, longitude: 103.86071, horizontal_accuracy: 12 };

  window.THEMES = {
    // Telegram's default day theme (note: its hint colour is below AA on white; the page corrects it).
    light: { bg_color: '#ffffff', secondary_bg_color: '#f0f0f0', text_color: '#000000', hint_color: '#999999',
      link_color: '#2481cc', button_color: '#3390ec', button_text_color: '#ffffff', destructive_text_color: '#e53935' },
    dark: { bg_color: '#212121', secondary_bg_color: '#181818', text_color: '#ffffff', hint_color: '#aaaaaa',
      link_color: '#8774e1', button_color: '#8774e1', button_text_color: '#ffffff', destructive_text_color: '#ff595a' },
    // A low-contrast custom theme, to prove the AA correction.
    washed: { bg_color: '#f4efe6', secondary_bg_color: '#e9e2d6', text_color: '#3b3a36', hint_color: '#c8bfae',
      link_color: '#e0a96d', button_color: '#f2c14e', button_text_color: '#ffffff', destructive_text_color: '#f28b82' },
  };

  window.SCENARIOS = {
    'outside-telegram': { initData: '', expect: { state: 'outside', text: ['Open this from Telegram'], calls: [] } },
    'no-sdk': { sdk: false, expect: { state: 'outside', calls: [] } },
    'sdk-failed-in-telegram': { sdk: false, hash: 'tgWebAppData=user%3D%257B%257D&tgWebAppVersion=8.0',
      expect: { state: 'sdk-failed', text: ['Couldn’t load check-in'], buttons: ['Reload'], calls: [] } },
    desktop: { platform: 'tdesktop', expect: { state: 'desktop', text: ['Open this on your phone'], calls: [] } },
    'telegram-web': { platform: 'weba', expect: { state: 'desktop', calls: [] } },
    'not-connected': { apiUrl: 'https://script.google.com/macros/s/PASTE_DEPLOYMENT_ID_HERE/exec', expect: { state: 'not-connected', text: ['API_URL'], calls: [] } },

    'member-no-session': { api: { status: [status({})] },
      expect: { state: 'no-session', text: ['No check-in open right now'], calls: ['status'], buttons: [] } },
    'admin-idle': { api: { status: [status({ isAdmin: true, sessionMinutes: 45 })] },
      expect: { state: 'admin-idle', buttons: ['Start check-in (45 min)'], calls: ['status'] } },
    'admin-start-then-check-in': {
      confirm: true,
      location: { lm: GPS },
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }],
        checkin: [CHECKED_IN],
      },
      steps: [{ click: 'Start check-in (60 min)' }, { waitState: 'admin-started', text: ['Check-in started', 'Open until 11:30', 'not checked in yet'] }, { click: 'Check in' }],
      expect: { state: 'checked-in', text: ['10:32', 'Started by Ada Admin'], focusInApp: true,
        calls: ['status', 'startSession', 'checkin'], confirmed: ['Start a 60-minute check-in for the group? It can’t be ended early.'] },
    },
    'admin-start-cancelled': {
      confirm: false,
      api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-idle', calls: ['status'] },
    },
    'double-tap-start': {
      confirm: true,
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }],
      },
      steps: [{ doubleClick: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', calls: ['status', 'startSession'], nativeConfirms: 0, confirmed: ['Start a 60-minute check-in for the group? It can’t be ended early.'] },
    },
    'admin-start-race': {
      confirm: true,
      api: {
        status: [status({ isAdmin: true }), status({ isAdmin: true, activeSession: SESSION })],
        startSession: [{ ok: false, code: 'SESSION_ACTIVE', message: 'A check-in is already open until 11:30, started by Ada Admin.', data: SESSION }],
      },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'ready', text: ['Ada Admin already started this check-in', 'not checked in yet'], buttons: ['Check in'], calls: ['status', 'startSession', 'status'] },
    },
    'admin-start-warning': {
      confirm: true,
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.',
          data: Object.assign({ warning: 'The group announcement could not be sent. Share the check-in link yourself.', shareLink: 'https://t.me/test_bot/checkin' }, SESSION) }],
      },
      steps: [{ click: 'Start check-in (60 min)' }, { waitState: 'admin-started' }, { click: 'Share check-in link' }],
      expect: { state: 'admin-started', text: ['announcement could not be sent'], buttons: ['Check in', 'Share check-in link'],
        openedLinks: ['https://t.me/share/url?url=https%3A%2F%2Ft.me%2Ftest_bot%2Fcheckin'] },
    },

    'member-auto-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', text: ['10:32', 'closes at 11:30'], buttons: ['Done'], calls: ['status', 'checkin'],
        sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 }, notText: ['Ada'] } },
    'already-checked-in': {
      api: { status: [status({ activeSession: MEMBER_SESSION, myCheckin: { at: '2026-09-21T02:31:00.000Z', atText: '10:31' } })] },
      expect: { state: 'checked-in', text: ['10:31', 'closes at 11:30'], calls: ['status'] } },
    'admin-auto-checkin': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', text: ['closes at 11:30', 'Started by Ada Admin'], notText: ['Open until'], calls: ['status', 'checkin'] } },

    'low-accuracy-then-retry': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'LOW_ACCURACY', message: 'Your location is not precise enough (±180 m). Move outdoors or near a window and try again.', data: { accuracyM: 180, maxAccuracyM: 100 } }, CHECKED_IN] },
      steps: [{ waitState: 'failed', text: ['Not checked in', 'Your location isn’t precise enough', '±180 m'] }, { click: 'Try again' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'], focusInApp: true } },
    'approximate-location': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'LOW_ACCURACY', message: 'Your location is not precise enough (±2800 m). Move outdoors or near a window and try again.', data: { accuracyM: 2800, maxAccuracyM: 100 } }] },
      expect: { state: 'failed', text: ['approximate location (±2.8 km)', 'Precise Location'], notText: ['Move outdoors'] } },
    'out-of-range': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 420 m from the venue. Check-in works within 150 m.', data: { distanceM: 420, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['Not checked in', 'too far from the venue', '420 m'], buttons: ['Try again'] } },
    'not-member': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'NOT_MEMBER', message: 'Only members of the group can check in. If you just joined, try again in a minute.' }] },
      expect: { state: 'failed', text: ['Members only'], buttons: ['Try again'] } },
    'session-just-closed': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'NO_ACTIVE_SESSION', message: 'No check-in is open right now.' }] },
      expect: { state: 'closed', text: ['Not checked in', 'closed before you got in'], buttons: ['Done'], calls: ['status', 'checkin'] } },
    'auth-expired-during-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'AUTH_EXPIRED', message: 'This page has been open too long. Close it and tap the Check in button in the group again.' }] },
      expect: { state: 'auth', text: ['Not checked in', 'This page timed out'], buttons: ['Close'] } },
    'network-during-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [{ network: true }] },
      expect: { state: 'failed', text: ['Not confirmed', 'won’t be counted twice'], notText: ['Not checked in'], calls: ['status', 'checkin', 'checkin'] } },
    'out-of-range-far': { location: { lm: GPS, browser: { latitude: 1.35, longitude: 103.95, accuracy: 10 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 12345 m from the venue. Check-in works within 150 m.', data: { distanceM: 12345, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['12.3 km from the venue'], notText: ['12345'] } },

    'location-denied': { location: { lm: null },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      steps: [{ waitState: 'location-denied', text: ['Not checked in', 'Location access is off'] }, { click: 'Open settings' }],
      expect: { state: 'location-denied', buttons: ['Try again', 'Open settings'], calls: ['status'], openedSettings: 1 } },
    'location-denied-repeat': { location: { lm: null },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      steps: [{ waitState: 'location-denied' }, { click: 'Try again' }],
      expect: { state: 'location-denied', text: ['still off'] } },
    'ios-denied-then-settings': { platform: 'ios', location: { lm: null, grantOnSettings: true },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      steps: [{ waitState: 'location-denied' }, { click: 'Open settings' }, { waitState: 'location-denied', text: ['tap Try again'] }, { click: 'Try again' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin'], openedSettings: 1 } },
    'ios-telegram-lacks-permission': { platform: 'ios', location: { lm: 'silent', asked: true, browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-denied', text: ['Location is off for Telegram', 'phone’s settings'], buttons: ['Try again'], calls: ['status'] } },
    'android-location-off': { location: { lm: GPS, deviceOff: true, browserError: 2 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-error', text: ['Turn on Location'], buttons: ['Try again'], notButtons: ['Open settings'] } },
    'android-stale-telegram-fix': {
      location: { lm: { latitude: 1.35, longitude: 103.94, horizontal_accuracy: 10 }, browser: { latitude: 1.28344, longitude: 103.86072, accuracy: 14 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 9200 m from the venue. Check-in works within 150 m.', data: { distanceM: 9200, radiusM: 150 } }, CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'],
        sentLocations: [{ lat: 1.35, lng: 103.94, accuracy: 10 }, { lat: 1.28344, lng: 103.86072, accuracy: 14 }] } },
    'android-telegram-fix-good': { location: { lm: GPS, browser: { latitude: 9, longitude: 9, accuracy: 5 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'ios-late-telegram-answer-wins': { platform: 'ios', location: { lm: GPS, lmDelay: 500, asked: true, browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'checked-in-large-text': { fontScale: 1.3, location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', stampFits: true } },
    'ios-uses-telegram-location': { platform: 'ios',
      location: { lm: GPS, browser: { latitude: 9, longitude: 9, accuracy: 5 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'ios-lm-no-accuracy-uses-browser': { platform: 'ios',
      location: { lm: { latitude: 1.28, longitude: 103.86, horizontal_accuracy: null }, browser: { latitude: 1.2836, longitude: 103.8607, accuracy: 9 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2836, lng: 103.8607, accuracy: 9 } } },
    'location-granted-in-settings': { location: { lm: null, grantOnSettings: true },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      steps: [{ waitState: 'location-denied' }, { click: 'Open settings' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin'] } },
    'old-client-browser-gps': { version: '7.10', location: { browser: { latitude: 1.2835, longitude: 103.8606, accuracy: 25 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2835, lng: 103.8606, accuracy: 25 } } },
    'lm-no-accuracy-uses-browser': {
      location: { lm: { latitude: 1.28, longitude: 103.86, horizontal_accuracy: null }, browser: { latitude: 1.2836, longitude: 103.8607, accuracy: 9 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2836, lng: 103.8607, accuracy: 9 } } },
    'browser-gps-denied': { version: '7.10', location: { browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-denied', text: ['Location is off for Telegram'], buttons: ['Try again'], notButtons: ['Open settings'] } },
    'gps-timeout': { version: '7.10', location: { browserError: 3 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-error', text: ['didn’t return a location in time'], buttons: ['Try again'] } },

    'busy-then-ok': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'The server is busy. Please try again in a moment.' }, CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'] } },
    'busy-twice': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'The server is busy. Please try again in a moment.' }] },
      expect: { state: 'failed', text: ['Busy right now'], calls: ['status', 'checkin', 'checkin'] } },
    'network-down': { api: { status: [{ network: true }] },
      expect: { state: 'failed', text: ['Couldn’t reach the server'], calls: ['status', 'status'] } },
    'apps-script-html-error': { api: { status: [{ html: true }, status({})] },
      expect: { state: 'no-session', calls: ['status', 'status'] } },
    'auth-expired': { api: { status: [{ ok: false, code: 'AUTH_EXPIRED', message: 'This page has been open too long. Close it and tap the Check in button in the group again.' }] },
      steps: [{ waitState: 'auth' }, { click: 'Close' }],
      expect: { state: 'auth', text: ['This page timed out'], closed: 1 } },
    'setup-error': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'SERVER_ERROR', message: 'Check-in is not set up yet (Config: SITE_LAT). Please tell an admin.' }] },
      expect: { state: 'failed', text: ['Something went wrong', 'SITE_LAT'] } },

    // Presentation-only states for screenshots and the layout audit.
    'loading': { api: { status: [{ pending: true }] }, expect: { state: 'loading', text: ['Still working'] } },
    'retrying': { api: { status: [{ network: true }, { pending: true }] }, expect: { state: 'loading', text: ['Trying again…'], calls: ['status', 'status'] } },
    'hostile-names': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: Object.assign({}, SESSION,
        { startedByName: 'Maximilian-Alexander Wolfeschlegelsteinhausenbergerdorff <img src=x onerror=alert(1)>' }) })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 12345 m from the venue. Check-in works within 150 m.', data: { distanceM: 12345, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['<img src=x onerror=alert(1)>'] } },
  };
})();
