/* Scripted scenarios for the Mini App harness (dev-only; never deployed).
 * Each scenario configures the mock Telegram client, the mock backend, the steps to
 * perform, and what must be true at the end. See harness.html and run.html. */
(function () {
  var SESSION = {
    sessionId: 'S-20260921-1030',
    opensAt: '2026-09-21T02:30:15.000Z',
    closesAt: '2026-09-21T03:30:15.000Z',
    closesAtText: '11:30',
    startedByName: 'Ada Admin',
  };
  var MEMBER_SESSION = { sessionId: SESSION.sessionId, opensAt: SESSION.opensAt, closesAt: SESSION.closesAt, closesAtText: '11:30' };
  var CHECKED_IN_BASE = { sessionId: SESSION.sessionId, at: '2026-09-21T02:32:07.000Z', atText: '10:32', closesAt: SESSION.closesAt, closesAtText: '11:30' };
  // groups/profile as the server sends them; the default is someone with nothing left to ask.
  function checkedIn(groups, profile) {
    return { ok: true, code: 'CHECKED_IN', message: 'Checked in at 10:32.', data: Object.assign({ groups: groups, profile: profile }, CHECKED_IN_BASE) };
  }
  var CHECKED_IN = checkedIn([], { fullName: 'Cy Member', group: '' });
  var GROUPS = ['Alpha', 'Bravo', 'Charlie'];
  function saved(fullName, group, groups) {
    return { ok: true, code: 'PROFILE_SAVED', message: 'Saved.', data: { groups: groups || GROUPS, profile: { fullName: fullName, group: group } } };
  }
  function SETTINGS_SAVED(sessionMinutes, radiusM, maxAccuracyM) {
    return { ok: true, code: 'SETTINGS_SAVED', message: 'Saved.', data: { sessionMinutes: sessionMinutes, radiusM: radiusM, maxAccuracyM: maxAccuracyM } };
  }
  var START_CONFIRM = 'Start a 60-minute check-in here? Members will need to be within 150 m of where you’re standing. It can’t be ended early.';
  var FRESH = { latitude: 1.2834, longitude: 103.8607, accuracy: 8 }; // the browser's fresh fix on Android
  function status(data) {
    return { ok: true, code: 'OK', message: '', data: Object.assign({ isAdmin: false, sessionMinutes: 60, radiusM: 150, maxAccuracyM: 100, activeSession: null, myCheckin: null }, data) };
  }
  var GPS = { latitude: 1.28345, longitude: 103.86071, horizontal_accuracy: 12 };

  window.THEMES = {
    // Telegram's default day theme (note: its hint colour is below AA on white; the page corrects it).
    light: { bg_color: '#ffffff', secondary_bg_color: '#f0f0f0', text_color: '#000000', hint_color: '#999999',
      link_color: '#2481cc', button_color: '#3390ec', button_text_color: '#ffffff', destructive_text_color: '#e53935' },
    dark: { bg_color: '#212121', secondary_bg_color: '#181818', text_color: '#ffffff', hint_color: '#aaaaaa',
      link_color: '#8774e1', button_color: '#8774e1', button_text_color: '#ffffff', destructive_text_color: '#ff595a' },
    // A low-contrast custom theme, to prove the AA correction.
    washed: { bg_color: '#f4efe6', secondary_bg_color: '#e9e2d6', text_color: '#3b3a36', hint_color: '#c8bfae',
      link_color: '#e0a96d', button_color: '#f2c14e', button_text_color: '#ffffff', destructive_text_color: '#f28b82' },
  };

  window.SCENARIOS = {
    'outside-telegram': { initData: '', expect: { state: 'outside', text: ['Open this from Telegram'], calls: [] } },
    'no-sdk': { sdk: false, expect: { state: 'outside', calls: [] } },
    'sdk-failed-in-telegram': { sdk: false, hash: 'tgWebAppData=user%3D%257B%257D&tgWebAppVersion=8.0',
      expect: { state: 'sdk-failed', text: ['Couldn’t load check-in'], buttons: ['Reload'], calls: [] } },
    desktop: { platform: 'tdesktop', expect: { state: 'desktop', text: ['Open this on your phone'], calls: [] } },
    'telegram-web': { platform: 'weba', expect: { state: 'desktop', calls: [] } },
    'not-connected': { apiUrl: 'https://script.google.com/macros/s/PASTE_DEPLOYMENT_ID_HERE/exec', expect: { state: 'not-connected', text: ['API_URL'], calls: [] } },

    'member-no-session': { api: { status: [status({})] },
      expect: { state: 'no-session', text: ['No check-in open right now'], calls: ['status'], buttons: [] } },
    'admin-idle': { api: { status: [status({ isAdmin: true, sessionMinutes: 45 })] },
      expect: { state: 'admin-idle', buttons: ['Start check-in (45 min)', 'Change settings'], calls: ['status'] } },

    // ---------- check-in settings (admins) ----------
    'admin-settings-open': { api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Change settings' }],
      expect: { state: 'settings', text: ['Check-in settings', 'For every check-in, whoever starts it.', 'How long check-in stays open', 'How close members must be', 'Location accuracy needed'],
        buttons: ['Save', 'Cancel'], inputValues: { 'set-minutes': '60', 'set-radius': '150', 'set-accuracy': '100' }, calls: ['status'] } },
    'admin-settings-save': { confirm: false,
      api: { status: [status({ isAdmin: true })], saveSettings: [SETTINGS_SAVED(45, 250, 80)] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { fill: ['#set-minutes', '45'] }, { fill: ['#set-radius', ' 250 '] },
        { fill: ['#set-accuracy', '80'] }, { click: 'Save' },
        { waitState: 'admin-idle', text: ['Saved: open 45\u00a0min, within 250\u00a0m, accuracy ±80\u00a0m or better.', 'within 250 m of you', 'next 45 minutes'] },
        { click: 'Start check-in (45 min)' }],
      expect: { state: 'admin-idle', buttons: ['Start check-in (45 min)', 'Change settings'], calls: ['status', 'saveSettings'],
        sentSettings: { sessionMinutes: 45, radiusM: 250, maxAccuracyM: 80 },
        confirmed: ['Start a 45-minute check-in here? Members will need to be within 250 m of where you’re standing. It can’t be ended early.'] } },
    'admin-settings-out-of-range': { api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { fill: ['#set-minutes', '1.5'] }, { fill: ['#set-radius', '5'] }, { click: 'Save' }],
      expect: { state: 'settings', text: ['Enter a whole number from 1 to 720.', 'Enter a whole number from 10 to 5000.'],
        invalid: ['set-minutes', 'set-radius'], focusId: 'set-minutes', focusInApp: true, calls: ['status'] } },
    'admin-settings-server-rejects': { api: { status: [status({ isAdmin: true })],
      saveSettings: [{ ok: false, code: 'INVALID_SETTINGS', message: 'Some settings are out of range.', data: { errors: { maxAccuracyM: 'Enter a whole number from 10 to 500.' } } }] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { click: 'Save' }],
      expect: { state: 'settings', text: ['Enter a whole number from 10 to 500.'], invalid: ['set-accuracy'], calls: ['status', 'saveSettings'] } },
    'admin-settings-network': { api: { status: [status({ isAdmin: true })], saveSettings: [{ network: true }] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { fill: ['#set-radius', '300'] }, { click: 'Save' }],
      expect: { state: 'settings', text: ['Couldn’t save. Check your connection and try again.'], inputValues: { 'set-radius': '300' }, buttons: ['Save', 'Cancel'] } },
    'admin-settings-not-admin': { api: { status: [status({ isAdmin: true })],
      saveSettings: [{ ok: false, code: 'NOT_ADMIN', message: 'Only admins of the group can change check-in settings.' }] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { click: 'Save' }],
      expect: { state: 'settings', text: ['Only admins of the group can change check-in settings.'] } },
    'admin-settings-cancel': { api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Change settings' }, { waitState: 'settings' }, { fill: ['#set-minutes', '15'] }, { click: 'Cancel' },
        { waitState: 'admin-idle', text: ['next 60 minutes'] }, { click: 'Change settings' }],
      expect: { state: 'settings', inputValues: { 'set-minutes': '60' }, notText: ['Saved:'], calls: ['status'] } },
    'admin-checked-in-settings': {
      api: { status: [status({ isAdmin: true, activeSession: SESSION, myCheckin: { at: '2026-09-21T02:31:00.000Z', atText: '10:31' },
        groups: [], profile: { fullName: 'LTA Ada Admin', group: '' } })], saveSettings: [SETTINGS_SAVED(60, 300, 100)] },
      steps: [{ waitState: 'checked-in' }, { click: 'Check-in settings' },
        { waitState: 'settings', text: ['Distance and accuracy apply straight away.', 'The time applies from the next check-in.'] },
        { fill: ['#set-radius', '300'] }, { click: 'Save' }],
      expect: { state: 'checked-in', text: ['10:31', 'Saved: open 60\u00a0min, within 300\u00a0m'], buttons: ['Check-in settings', 'Done'],
        sentSettings: { sessionMinutes: 60, radiusM: 300, maxAccuracyM: 100 } } },
    'admin-settings-during-session': {
      api: { status: [status({ isAdmin: true, activeSession: SESSION, myCheckin: { at: '2026-09-21T02:31:00.000Z', atText: '10:31' },
        groups: ['Alpha', 'Bravo'], profile: { fullName: 'LTA Ada Admin', group: 'Alpha' } })] },
      steps: [{ waitState: 'checked-in', text: ['Alpha · LTA Ada Admin'] }, { click: 'Check-in settings' }],
      expect: { state: 'settings', text: ['apply straight away'], buttons: ['Save', 'Cancel'] } },
    'admin-settings-large-text': { fontScale: 1.3, api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Change settings' }],
      expect: { state: 'settings', buttons: ['Save', 'Cancel'] } },
    'admin-start-then-check-in': {
      confirm: true,
      location: { lm: GPS },
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }],
        checkin: [CHECKED_IN],
      },
      steps: [{ click: 'Start check-in (60 min)' }, { waitState: 'admin-started', text: ['Check-in started', 'Open until 11:30', 'The check-in point is where you’re standing', 'not checked in yet'] }, { click: 'Check in' }],
      expect: { state: 'checked-in', text: ['10:32', 'Started by Ada Admin'], focusInApp: true,
        calls: ['status', 'startSession', 'checkin'], confirmed: [START_CONFIRM] },
    },
    'admin-start-cancelled': {
      confirm: false,
      api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-idle', calls: ['status'] },
    },
    'double-tap-start': {
      confirm: true,
      location: { lm: GPS },
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }],
      },
      steps: [{ doubleClick: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', calls: ['status', 'startSession'], nativeConfirms: 0, confirmed: [START_CONFIRM] },
    },
    'admin-start-race': {
      confirm: true,
      location: { lm: GPS },
      api: {
        status: [status({ isAdmin: true }), status({ isAdmin: true, activeSession: SESSION })],
        startSession: [{ ok: false, code: 'SESSION_ACTIVE', message: 'A check-in is already open until 11:30, started by Ada Admin.', data: SESSION }],
      },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'ready', text: ['Ada Admin already started this check-in', 'not checked in yet', 'Open until 11:30'], notText: ['· started by'], buttons: ['Check in'], calls: ['status', 'startSession', 'status'] },
    },
    'admin-start-warning': {
      confirm: true,
      location: { lm: GPS },
      api: {
        status: [status({ isAdmin: true })],
        startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.',
          data: Object.assign({ warning: 'The group announcement could not be sent. Share the check-in link yourself.', shareLink: 'https://t.me/test_bot/checkin' }, SESSION) }],
      },
      steps: [{ click: 'Start check-in (60 min)' }, { waitState: 'admin-started' }, { click: 'Share check-in link' }],
      expect: { state: 'admin-started', text: ['announcement could not be sent'], buttons: ['Share check-in link', 'Check in'],
        openedLinks: ['https://t.me/share/url?url=https%3A%2F%2Ft.me%2Ftest_bot%2Fcheckin'] },
    },

    'member-auto-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', text: ['10:32', 'closes at 11:30'], buttons: ['Done'], calls: ['status', 'checkin'],
        sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 }, notText: ['Ada'] } },
    'already-checked-in': {
      api: { status: [status({ activeSession: MEMBER_SESSION, myCheckin: { at: '2026-09-21T02:31:00.000Z', atText: '10:31' } })] },
      expect: { state: 'checked-in', text: ['10:31', 'closes at 11:30'], calls: ['status'] } },
    'admin-auto-checkin': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', text: ['closes at 11:30', 'Started by Ada Admin'], notText: ['Open until'], calls: ['status', 'checkin'] } },

    'low-accuracy-then-retry': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'LOW_ACCURACY', message: 'Your location is not precise enough (±180 m). Move outdoors or near a window and try again.', data: { accuracyM: 180, maxAccuracyM: 100 } }, CHECKED_IN] },
      steps: [{ waitState: 'failed', text: ['Not checked in', 'Your location isn’t precise enough', 'Accuracy ±180 m (needs ±100 m)'] }, { click: 'Try again' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'], focusInApp: true } },
    'approximate-location': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'LOW_ACCURACY', message: 'Your location is not precise enough (±2800 m). Move outdoors or near a window and try again.', data: { accuracyM: 2800, maxAccuracyM: 100 } }] },
      expect: { state: 'failed', text: ['approximate location (±2.8 km)', 'Precise Location'], notText: ['Move outdoors'] } },
    'out-of-range': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 420 m from the venue. Check-in works within 150 m.', data: { distanceM: 420, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['Not checked in', 'too far from the venue', '420 m'], buttons: ['Try again'] } },
    'not-member': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'NOT_MEMBER', message: 'Only members of the group can check in. If you just joined, try again in a minute.' }] },
      expect: { state: 'failed', text: ['Members only'], buttons: ['Try again'] } },
    'session-just-closed': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'NO_ACTIVE_SESSION', message: 'No check-in is open right now.' }] },
      expect: { state: 'closed', text: ['Not checked in', 'closed before you got in'], buttons: ['Done'], calls: ['status', 'checkin'] } },
    'auth-expired-during-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'AUTH_EXPIRED', message: 'This page has been open too long. Close it and tap the Check in button in the group again.' }] },
      expect: { state: 'auth', text: ['Not checked in', 'This page timed out'], buttons: ['Close'] } },
    'network-during-checkin': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [{ network: true }] },
      expect: { state: 'failed', text: ['Not confirmed', 'won’t be counted twice'], notText: ['Not checked in'], calls: ['status', 'checkin', 'checkin', 'checkin'] } },
    'out-of-range-far': { location: { lm: GPS, browser: { latitude: 1.35, longitude: 103.95, accuracy: 10 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are more than 1 km from the venue.', data: { distanceM: null, beyondM: 1000, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['more than 1 km from the venue'], notText: ['1.0 km'] } },

    'location-denied': { location: { lm: null },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      steps: [{ waitState: 'location-denied', text: ['Not checked in', 'Location access is off'] }, { click: 'Open settings' }],
      expect: { state: 'location-denied', buttons: ['Try again', 'Open settings'], calls: ['status'], openedSettings: 1 } },
    'location-denied-repeat': { location: { lm: null },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      steps: [{ waitState: 'location-denied' }, { click: 'Try again' }],
      expect: { state: 'location-denied', text: ['still off'] } },
    'ios-denied-then-settings': { platform: 'ios', location: { lm: null, grantOnSettings: true },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      steps: [{ waitState: 'location-denied' }, { click: 'Open settings' }, { waitState: 'location-denied', text: ['tap Try again'] }, { click: 'Try again' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin'], openedSettings: 1 } },
    'ios-telegram-lacks-permission': { platform: 'ios', location: { lm: 'silent', asked: true, browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-denied', text: ['Location is off for Telegram', 'phone’s settings'], buttons: ['Try again'], calls: ['status'] } },
    'android-location-off': { location: { lm: GPS, deviceOff: true, browserError: 2 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-error', text: ['Turn on Location'], buttons: ['Try again'], notButtons: ['Open settings'] } },
    'android-stale-telegram-fix': {
      location: { lm: { latitude: 1.35, longitude: 103.94, horizontal_accuracy: 10 }, browser: { latitude: 1.28344, longitude: 103.86072, accuracy: 14 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 9200 m from the venue. Check-in works within 150 m.', data: { distanceM: 9200, radiusM: 150 } }, CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'],
        sentLocations: [{ lat: 1.35, lng: 103.94, accuracy: 10 }, { lat: 1.28344, lng: 103.86072, accuracy: 14 }] } },
    'android-telegram-fix-good': { location: { lm: GPS, browser: { latitude: 9, longitude: 9, accuracy: 5 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'ios-late-telegram-answer-wins': { platform: 'ios', location: { lm: GPS, lmDelay: 500, asked: true, browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'checked-in-large-text': { fontScale: 1.3, location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', stampFits: true } },
    'ios-uses-telegram-location': { platform: 'ios',
      location: { lm: GPS, browser: { latitude: 9, longitude: 9, accuracy: 5 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'ios-lm-no-accuracy-uses-browser': { platform: 'ios',
      location: { lm: { latitude: 1.28, longitude: 103.86, horizontal_accuracy: null }, browser: { latitude: 1.2836, longitude: 103.8607, accuracy: 9 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2836, lng: 103.8607, accuracy: 9 } } },
    'location-granted-in-settings': { location: { lm: null, grantOnSettings: true },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      steps: [{ waitState: 'location-denied' }, { click: 'Open settings' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin'] } },
    'old-client-browser-gps': { version: '7.10', location: { browser: { latitude: 1.2835, longitude: 103.8606, accuracy: 25 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2835, lng: 103.8606, accuracy: 25 } } },
    'lm-no-accuracy-uses-browser': {
      location: { lm: { latitude: 1.28, longitude: 103.86, horizontal_accuracy: null }, browser: { latitude: 1.2836, longitude: 103.8607, accuracy: 9 } },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', sentLocation: { lat: 1.2836, lng: 103.8607, accuracy: 9 } } },
    'browser-gps-denied': { version: '7.10', location: { browserError: 1 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-denied', text: ['Location is off for Telegram'], buttons: ['Try again'], notButtons: ['Open settings'] } },
    'gps-timeout': { version: '7.10', location: { browserError: 3 },
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-error', text: ['didn’t return a location in time'], buttons: ['Try again'] } },

    'busy-then-ok': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'The server is busy. Please try again in a moment.' }, CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin'] } },
    'busy-twice': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'The server is busy. Please try again in a moment.' }] },
      expect: { state: 'failed', text: ['Busy right now', 'Not checked in'], waitMs: 20000 } },
    // Still busy when the retry time runs out, but a queued copy did record them.
    'busy-but-recorded': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION }),
        status({ activeSession: MEMBER_SESSION, myCheckin: { at: '2026-09-21T02:32:07.000Z', atText: '10:32' } })],
        checkin: [{ ok: false, code: 'BUSY', message: 'The server is busy. Please try again in a moment.' }] },
      expect: { state: 'checked-in', text: ['10:32'], notText: ['Busy right now'], waitMs: 20000 } },
    // A crowd: the server is busy several times in a row, then records the check-in.
    'crowd-busy-then-in': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'busy' }, { ok: false, code: 'BUSY', message: 'busy' }, { ok: false, code: 'BUSY', message: 'busy' }, CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'checkin', 'checkin', 'checkin'], waitMs: 20000 } },
    'crowd-busy-message': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'BUSY', message: 'busy' }, { pending: true }] },
      expect: { state: 'loading', text: ['Trying again…', 'Lots of people are checking in right now'] } },
    'network-down': { api: { status: [{ network: true }] },
      expect: { state: 'failed', text: ['Couldn’t reach the server'], calls: ['status', 'status', 'status'] } },
    // Replies come through the frame first; a normal copy follows if it is slow or fails.
    'frame-first': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], vias: ['frame', 'frame'] } },
    'slow-frame-fetch-wins': { location: { lm: GPS },
      api: { status: [{ pending: true }, status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', viasStart: ['frame', 'fetch'] } },
    'lost-frame-reply-then-fetch': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [{ html: true }, CHECKED_IN] },
      expect: { state: 'checked-in', viasStart: ['frame', 'frame', 'fetch'] } },
    'start-twin-reports-mine': {
      confirm: true,
      location: { lm: GPS },
      api: { status: [status({ isAdmin: true })],
        startSession: [{ pending: true }, { ok: false, code: 'SESSION_ACTIVE', message: 'A check-in is already open until 11:30, started by Ada Admin.',
          data: Object.assign({ startedByMe: true }, SESSION) }] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', text: ['Check-in started'], notText: ['already started'] } },
    'apps-script-html-error': { api: { status: [{ html: true }, status({})] },
      expect: { state: 'no-session', viasStart: ['frame', 'fetch'] } },
    'auth-expired': { api: { status: [{ ok: false, code: 'AUTH_EXPIRED', message: 'This page has been open too long. Close it and tap the Check in button in the group again.' }] },
      steps: [{ waitState: 'auth' }, { click: 'Close' }],
      expect: { state: 'auth', text: ['This page timed out'], closed: 1 } },
    'setup-error': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'SERVER_ERROR', message: 'Check-in is not set up yet (Config: RADIUS_M). Please tell an admin.' }] },
      expect: { state: 'failed', text: ['Something went wrong', 'RADIUS_M'] } },

    // ---------- the admin's location is the check-in point ----------
    'admin-start-android-fresh-fix': {
      confirm: true,
      location: { lm: { latitude: 1.35, longitude: 103.94, horizontal_accuracy: 10 }, browser: FRESH },
      api: { status: [status({ isAdmin: true })], startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', calls: ['status', 'startSession'], startLocation: { lat: 1.2834, lng: 103.8607, accuracy: 8 } } },
    'admin-start-ios-telegram-fix': {
      platform: 'ios', confirm: true,
      location: { lm: GPS, browser: { latitude: 9, longitude: 9, accuracy: 5 } },
      api: { status: [status({ isAdmin: true })], startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', startLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'admin-start-low-accuracy-then-retry': {
      confirm: true,
      location: { lm: GPS },
      api: { status: [status({ isAdmin: true })], startSession: [
        { ok: false, code: 'LOW_ACCURACY', message: 'Your location is not precise enough (±180 m) to set the check-in point.', data: { accuracyM: 180, maxAccuracyM: 100 } },
        { ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }] },
      steps: [{ click: 'Start check-in (60 min)' }, { waitState: 'failed', text: ['Not started', 'Your location isn’t precise enough', 'Accuracy ±180 m (needs ±100 m)'] }, { click: 'Try again' }],
      expect: { state: 'admin-started', calls: ['status', 'startSession', 'startSession'], confirmed: [START_CONFIRM], notText: ['Not checked in'] } },
    'admin-start-location-denied': {
      confirm: true,
      location: { lm: null },
      api: { status: [status({ isAdmin: true })] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'location-denied', text: ['Not started', 'Location access is off', 'Starting a check-in uses your location'], notText: ['Not checked in'], calls: ['status'] } },
    'admin-out-of-range-moves-point': {
      confirm: true,
      location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 2100 m from the venue.', data: { distanceM: 2100, radiusM: 150 } }, CHECKED_IN],
        moveSite: [{ ok: true, code: 'SITE_MOVED', message: 'The check-in point is now where you are.', data: SESSION }] },
      steps: [{ waitState: 'failed', text: ['too far from the check-in point', '2.1 km from it', 'move it to where you are'] }, { click: 'Move check-in point here' }],
      expect: { state: 'checked-in', calls: ['status', 'checkin', 'moveSite', 'checkin'], text: ['The check-in point is now where you’re standing'],
        confirmed: ['Move the check-in point 2.1 km, to where you’re standing? Members near the old spot won’t be able to check in.'],
        startLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'admin-out-of-range-buttons': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 2100 m from the venue.', data: { distanceM: 2100, radiusM: 150 } }] },
      expect: { state: 'failed', buttons: ['Try again', 'Move check-in point here'] } },
    'admin-no-site': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })],
        checkin: [{ ok: false, code: 'NO_SITE', message: 'This check-in has no check-in point yet.' }] },
      expect: { state: 'failed', text: ['Check-in isn’t ready yet', 'Set it to where you’re standing'], buttons: ['Set check-in point here'] } },
    'member-no-site': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'NO_SITE', message: 'This check-in has no check-in point yet. An admin needs to open check-in and tap “Move check-in point here”.' }] },
      expect: { state: 'failed', text: ['Check-in isn’t ready yet', 'Ask an admin to set it'], notText: ['Move check-in point'], buttons: ['Try again'] } },
    'member-out-of-range-no-move': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 420 m from the venue.', data: { distanceM: 420, radiusM: 150 } }] },
      expect: { state: 'failed', buttons: ['Try again'], notText: ['check-in point'] } },
    'member-out-of-range-rounded': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are about 200 m from the venue.', data: { distanceM: 200, rounded: true, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['about 200 m from the venue', 'works within 150 m'] } },
    'member-out-of-range-capped': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are not within 150 m of the venue.', data: { distanceM: null, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['not within 150 m of the venue'] } },

    // ---------- speed: location found while the server answers ----------
    'returning-member-overlap': { location: { lm: GPS, preGranted: true }, startParam: 'open', apiDelay: 400,
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], locationDuringStatus: true,
        sentLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 } } },
    'first-visit-no-early-location': { location: { lm: GPS }, apiDelay: 300,
      api: { status: [status({})] },
      expect: { state: 'no-session', calls: ['status'], noLocationRequest: true } },
    'first-visit-asks-after-status': { location: { lm: GPS }, apiDelay: 300,
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], locationAfterStatus: true } },
    'returning-member-no-hint': { location: { lm: GPS, preGranted: true }, apiDelay: 300,
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [CHECKED_IN] },
      expect: { state: 'checked-in', calls: ['status', 'checkin'], locationAfterStatus: true } },
    'returning-member-no-session': { location: { lm: GPS, preGranted: true },
      api: { status: [status({})] },
      expect: { state: 'no-session', calls: ['status'], noLocationRequest: true } },
    'returning-member-stale-button': { location: { lm: GPS, preGranted: true }, startParam: 'open',
      api: { status: [status({})] },
      expect: { state: 'no-session', calls: ['status'] } },
    'returning-member-early-denied': { location: { lm: null, preGranted: true }, startParam: 'open',
      api: { status: [status({ activeSession: MEMBER_SESSION })] },
      expect: { state: 'location-denied', calls: ['status'], locationRequests: 1 } },
    'ios-returning-no-browser-probe-without-session': { platform: 'ios', location: { lm: 'silent', preGranted: true, browserError: 1 },
      api: { status: [status({})] },
      expect: { state: 'no-session', calls: ['status'], noLocationRequest: true, noBrowserLocation: true } },
    'admin-start-fresh-fix-slow': {
      confirm: true,
      location: { lm: GPS, browser: FRESH, browserDelay: 3000 },
      api: { status: [status({ isAdmin: true })], startSession: [{ ok: true, code: 'SESSION_STARTED', message: 'Check-in is open until 11:30.', data: SESSION }] },
      steps: [{ click: 'Start check-in (60 min)' }],
      expect: { state: 'admin-started', startLocation: { lat: 1.28345, lng: 103.86071, accuracy: 12 }, text: ['last known position'] } },

    // ---------- group, rank and full name ----------
    'profile-first-time': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)], saveProfile: [saved('CPL Cy Member', 'Bravo')] },
      steps: [{ waitState: 'profile', text: ['You’re on the list', 'One quick question', 'Which group are you in?', 'Rank and full name'] },
        { fill: ['#full-name', 'CPL Cy Member'] }, { tap: 'Bravo' }],
      expect: { state: 'checked-in', text: ['10:32', 'Bravo · CPL Cy Member', 'Change'], buttons: ['Done'],
        sentProfile: { fullName: 'CPL Cy Member', group: 'Bravo' }, calls: ['status', 'checkin', 'saveProfile'] } },
    // Not prefilled from Telegram: a display name has no rank, and is often a nickname.
    'profile-picker': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)] },
      expect: { state: 'profile', choices: GROUPS, inputValue: '', placeholder: 'e.g. CPL Tan Wei Ming', buttons: [] } },
    'profile-name-untouched': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)] },
      steps: [{ waitState: 'profile' }, { tap: 'Alpha' }],
      expect: { state: 'profile', text: ['Enter your rank and full name first.'], invalid: ['full-name'], focusId: 'full-name', focusInApp: true, calls: ['status', 'checkin'] } },
    'profile-typed-name': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)], saveProfile: [saved('Cy Tan', 'Alpha')] },
      steps: [{ waitState: 'profile' }, { fill: ['#full-name', '  Cy   Tan '] }, { tap: 'Alpha' }],
      expect: { state: 'checked-in', text: ['Alpha · Cy Tan'], sentProfile: { fullName: 'Cy Tan', group: 'Alpha' } } },
    'profile-empty-name': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)] },
      steps: [{ waitState: 'profile' }, { fill: ['#full-name', '   '] }, { tap: 'Alpha' }],
      expect: { state: 'profile', text: ['Enter your rank and full name first.'], calls: ['status', 'checkin'] } },
    'profile-returning': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: 'Bravo' })] },
      expect: { state: 'checked-in', text: ['Bravo · Cy Tan', 'Change'], buttons: ['Done'], calls: ['status', 'checkin'] } },
    'profile-change': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: 'Bravo' })],
        saveProfile: [saved('Cy Tan', 'Charlie')] },
      steps: [{ waitState: 'checked-in' }, { tap: 'Change' }, { waitState: 'profile', text: ['Which group are you in?'] }, { tap: 'Charlie' }],
      expect: { state: 'checked-in', text: ['Charlie · Cy Tan'], sentProfile: { fullName: 'Cy Tan', group: 'Charlie' } } },
    'profile-change-open': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: 'Bravo' })] },
      steps: [{ waitState: 'checked-in' }, { tap: 'Change' }],
      expect: { state: 'profile', buttons: ['Save', 'Cancel'], inputValue: 'Cy Tan', notText: ['One quick question'] } },
    'profile-change-save-name': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: 'Bravo' })],
        saveProfile: [saved('Cy Tan-Lim', 'Bravo')] },
      steps: [{ waitState: 'checked-in' }, { tap: 'Change' }, { waitState: 'profile' }, { fill: ['#full-name', 'Cy Tan-Lim'] }, { click: 'Save' }],
      expect: { state: 'checked-in', text: ['Bravo · Cy Tan-Lim'], sentProfile: { fullName: 'Cy Tan-Lim', group: 'Bravo' } } },
    'profile-large-text': { fontScale: 1.3, location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)] },
      expect: { state: 'profile', stampFits: true } },
    'profile-change-cancel': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: 'Bravo' })] },
      steps: [{ waitState: 'checked-in' }, { tap: 'Change' }, { waitState: 'profile' }, { click: 'Cancel' }],
      expect: { state: 'checked-in', text: ['Bravo · Cy Tan'], calls: ['status', 'checkin'] } },
    'profile-no-groups': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn([], null)], saveProfile: [saved('CPL Cy Member', '', [])] },
      steps: [{ waitState: 'profile', text: ['Rank and full name'], notText: ['Which group'] }, { fill: ['#full-name', 'CPL Cy Member'] }, { click: 'Save name' }],
      expect: { state: 'checked-in', text: ['CPL Cy Member', 'Change'], sentProfile: { fullName: 'CPL Cy Member', group: '' } } },
    'profile-group-removed': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, { fullName: 'Cy Tan', group: '' })] },
      expect: { state: 'profile', choices: GROUPS, inputValue: null, text: ['group list has changed'], notText: ['Rank and full name'], buttons: [] } },
    'profile-save-network-error': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)], saveProfile: [{ network: true }] },
      steps: [{ waitState: 'profile' }, { fill: ['#full-name', 'Cy Tan'] }, { tap: 'Alpha' }],
      expect: { state: 'profile', text: ['10:32', 'You’re still checked in'], inputValue: 'Cy Tan', calls: ['status', 'checkin', 'saveProfile', 'saveProfile', 'saveProfile'] } },
    'profile-invalid-group': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [checkedIn(GROUPS, null)],
        saveProfile: [{ ok: false, code: 'INVALID_GROUP', message: 'That group isn’t on the list any more. Please pick one again.', data: { groups: ['Alpha', 'Delta'] } }] },
      steps: [{ waitState: 'profile' }, { fill: ['#full-name', 'CPL Cy Tan'] }, { tap: 'Bravo' }],
      expect: { state: 'profile', choices: ['Alpha', 'Delta'], text: ['isn’t on the list any more'] } },
    'profile-on-reopen': {
      api: { status: [status({ activeSession: MEMBER_SESSION, myCheckin: { at: '2026-09-21T02:31:00.000Z', atText: '10:31' }, groups: GROUPS, profile: null })] },
      expect: { state: 'profile', text: ['10:31', 'Which group are you in?'], calls: ['status'] } },
    'profile-older-server': { location: { lm: GPS },
      api: { status: [status({ activeSession: MEMBER_SESSION })], checkin: [{ ok: true, code: 'CHECKED_IN', message: '', data: CHECKED_IN_BASE }] },
      expect: { state: 'checked-in', buttons: ['Done'], notText: ['Change', 'Which group'] } },
    'profile-many-long-groups': { location: { lm: GPS }, tgUser: { id: 42, first_name: 'Maximilian-Alexander', last_name: 'Wolfeschlegelsteinhausenbergerdorff' },
      api: { status: [status({ isAdmin: true, activeSession: SESSION })], checkin: [checkedIn(['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot',
        'Youth ministry (Saturday evening)', 'Worship team', 'Ushers & welcome', '10', 'Hospitality and refreshments crew', 'Tech'], null)] },
      expect: { state: 'profile', text: ['Started by Ada Admin'] } },

    // Presentation-only states for screenshots and the layout audit.
    'loading': { api: { status: [{ pending: true }] }, expect: { state: 'loading', text: ['Still working'] } },
    'retrying': { api: { status: [{ network: true }, { pending: true }] }, expect: { state: 'loading', text: ['Trying again…'], viasStart: ['frame', 'fetch'], waitMs: 10000 } },
    'hostile-names': { location: { lm: GPS },
      api: { status: [status({ isAdmin: true, activeSession: Object.assign({}, SESSION,
        { startedByName: 'Maximilian-Alexander Wolfeschlegelsteinhausenbergerdorff <img src=x onerror=alert(1)>' }) })],
        checkin: [{ ok: false, code: 'OUT_OF_RANGE', message: 'You are 12345 m from the venue. Check-in works within 150 m.', data: { distanceM: 12345, radiusM: 150 } }] },
      expect: { state: 'failed', text: ['<img src=x onerror=alert(1)>'] } },
  };
})();
